### ISSUE TITLE
Changed files without filenames

### ISSUE THREAD

**Issue by tbreuss** [PHPGangsta/FileWatcher#1]
On Line Number 95 it should be

$changedFiles[$intersectKey] = $masterHashes[$intersectKey];

instead of

$changedFiles[] = $masterHashes[$intersectKey];

**Comment by PHPGangsta** [comment]
Hi,

could you please tell why the key should be $intersectKey? The $changedFiles should be a newly created array with numeric indices, it does not have to be indexed by $intersectKeys I think. Or could you please explain the difference? Where are the keys of that array used?

Michael

**Comment by tbreuss** [comment]
Hi Michael

because the numeric indexes give no information about which files have changed. 
This was the case in my environment. Or am i wrong?

Cheers,
Thomas

Von meinem iPad gesendet

Am 16.01.2012 um 18:41 schrieb Michael Kliewe reply@reply.github.com:

**Comment by PHPGangsta** [comment]
You are right, that makes sense! I have added it. See new version. Thanks!

**Comment by abmmhasan** [comment]
Hi PHPGangsta, as far you confirmed the issue solved! Why not close this issue?

**Comment by PHPGangsta** [comment]
You are right.. Back then I wanted to leave it open for diskussion for a day and then close it. Thanks for the reminder ;-)
